name: Python CI/CD Pipeline
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use an Ubuntu machine for running the pipeline

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Gets the latest code from the repository

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Installs Python 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8  # Install testing and linting tools

    - name: Run Linter (flake8)
      run: flake8 app.py test_app.py --max-line-length=88  # Ensures code quality

    - name: Run Tests
      run: pytest test_app.py  # Runs test cases